//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaltStackers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Activity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Activity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaltStackers.Resources.Activity", typeof(Activity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to Bank Gateway &apos;{0}&apos;.
        /// </summary>
        public static string AddPayment {
            get {
                return ResourceManager.GetString("AddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction &apos;{0}&apos; tracking number &apos;{1}&apos;.
        /// </summary>
        public static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block user &apos;{0}&apos;.
        /// </summary>
        public static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new bank gateway &apos;{0}&apos;.
        /// </summary>
        public static string CreateNewBankGateway {
            get {
                return ResourceManager.GetString("CreateNewBankGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new role &apos;{0}&apos;.
        /// </summary>
        public static string CreateNewRole {
            get {
                return ResourceManager.GetString("CreateNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new terminal &apos;{0}&apos;.
        /// </summary>
        public static string CreateNewTerminal {
            get {
                return ResourceManager.GetString("CreateNewTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new organization &apos;{0}&apos;.
        /// </summary>
        public static string CreateOrganization {
            get {
                return ResourceManager.GetString("CreateOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a service request of type &apos;{0}&apos;.
        /// </summary>
        public static string CreateServiceRequest {
            get {
                return ResourceManager.GetString("CreateServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user &apos;{0}&apos;.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete bank gateway &apos;{0}&apos;.
        /// </summary>
        public static string DeleteBankGateway {
            get {
                return ResourceManager.GetString("DeleteBankGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete organization &apos;{0}&apos;.
        /// </summary>
        public static string DeleteOrganization {
            get {
                return ResourceManager.GetString("DeleteOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete role &apos;{0}&apos;.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete terminal &apos;{0}&apos;.
        /// </summary>
        public static string DeleteTerminal {
            get {
                return ResourceManager.GetString("DeleteTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bank gateway &apos;{0}&apos;.
        /// </summary>
        public static string EditBankGateway {
            get {
                return ResourceManager.GetString("EditBankGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit organization &apos;{0}&apos;.
        /// </summary>
        public static string EditOrganization {
            get {
                return ResourceManager.GetString("EditOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit request &apos;{0}&apos;.
        /// </summary>
        public static string EditRequest {
            get {
                return ResourceManager.GetString("EditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role &apos;{0}&apos;.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit terminal &apos;{0}&apos;.
        /// </summary>
        public static string EditTerminal {
            get {
                return ResourceManager.GetString("EditTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user &apos;{0}&apos;.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in system.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged off from system.
        /// </summary>
        public static string LoggedOff {
            get {
                return ResourceManager.GetString("LoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save request &apos;{0}&apos;.
        /// </summary>
        public static string SaveRequest {
            get {
                return ResourceManager.GetString("SaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock user &apos;{0}&apos;.
        /// </summary>
        public static string UnblockUser {
            get {
                return ResourceManager.GetString("UnblockUser", resourceCulture);
            }
        }
    }
}
