//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaltStackers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Health {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Health() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaltStackers.Resources.Health", typeof(Health).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Level.
        /// </summary>
        public static string ActivityLevel {
            get {
                return ResourceManager.GetString("ActivityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Levels.
        /// </summary>
        public static string ActivityLevels {
            get {
                return ResourceManager.GetString("ActivityLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Description.
        /// </summary>
        public static string AllergyDescription {
            get {
                return ResourceManager.GetString("AllergyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Of Alcohol.
        /// </summary>
        public static string AmountOfAlcohol {
            get {
                return ResourceManager.GetString("AmountOfAlcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Of Water.
        /// </summary>
        public static string AmountOfWater {
            get {
                return ResourceManager.GetString("AmountOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Types.
        /// </summary>
        public static string BloodTypes {
            get {
                return ResourceManager.GetString("BloodTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Fat.
        /// </summary>
        public static string BodyFat {
            get {
                return ResourceManager.GetString("BodyFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrate.
        /// </summary>
        public static string Carbohydrate {
            get {
                return ResourceManager.GetString("Carbohydrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol.
        /// </summary>
        public static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Factor.
        /// </summary>
        public static string ConversionFactor {
            get {
                return ResourceManager.GetString("ConversionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking Days.
        /// </summary>
        public static string CookingDays {
            get {
                return ResourceManager.GetString("CookingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Stresses.
        /// </summary>
        public static string CurrentStresses {
            get {
                return ResourceManager.GetString("CurrentStresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet.
        /// </summary>
        public static string Diet {
            get {
                return ResourceManager.GetString("Diet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dietary Fiber.
        /// </summary>
        public static string DietaryFiber {
            get {
                return ResourceManager.GetString("DietaryFiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diets.
        /// </summary>
        public static string Diets {
            get {
                return ResourceManager.GetString("Diets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Treatment.
        /// </summary>
        public static string DiseaseTreatment {
            get {
                return ResourceManager.GetString("DiseaseTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dislike Foods.
        /// </summary>
        public static string DislikeFoods {
            get {
                return ResourceManager.GetString("DislikeFoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs Description.
        /// </summary>
        public static string DrugsDescription {
            get {
                return ResourceManager.GetString("DrugsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Physician Recommendations.
        /// </summary>
        public static string FamilyPhysicianRecommendations {
            get {
                return ResourceManager.GetString("FamilyPhysicianRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Foods.
        /// </summary>
        public static string FavoriteFoods {
            get {
                return ResourceManager.GetString("FavoriteFoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Personality.
        /// </summary>
        public static string FoodPersonality {
            get {
                return ResourceManager.GetString("FoodPersonality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden Foods.
        /// </summary>
        public static string ForbiddenFoods {
            get {
                return ResourceManager.GetString("ForbiddenFoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Allergy.
        /// </summary>
        public static string HasAllergy {
            get {
                return ResourceManager.GetString("HasAllergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Challenging Job.
        /// </summary>
        public static string HasChallengingJob {
            get {
                return ResourceManager.GetString("HasChallengingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Personal Trainer.
        /// </summary>
        public static string HasPersonalTrainer {
            get {
                return ResourceManager.GetString("HasPersonalTrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Goals.
        /// </summary>
        public static string HealthGoals {
            get {
                return ResourceManager.GetString("HealthGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Problems.
        /// </summary>
        public static string HealthProblems {
            get {
                return ResourceManager.GetString("HealthProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy Diet Knowledge.
        /// </summary>
        public static string HealthyDietKnowledge {
            get {
                return ResourceManager.GetString("HealthyDietKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Units.
        /// </summary>
        public static string HeightUnits {
            get {
                return ResourceManager.GetString("HeightUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Type.
        /// </summary>
        public static string IngredientType {
            get {
                return ResourceManager.GetString("IngredientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Type Unit.
        /// </summary>
        public static string IngredientTypeUnit {
            get {
                return ResourceManager.GetString("IngredientTypeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Usages.
        /// </summary>
        public static string IngredientUsages {
            get {
                return ResourceManager.GetString("IngredientUsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        public static string Iron {
            get {
                return ResourceManager.GetString("Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Athlete.
        /// </summary>
        public static string IsAthlete {
            get {
                return ResourceManager.GetString("IsAthlete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Percent.
        /// </summary>
        public static string IsPercent {
            get {
                return ResourceManager.GetString("IsPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Smoke Quitted.
        /// </summary>
        public static string IsSmokeQuitted {
            get {
                return ResourceManager.GetString("IsSmokeQuitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Smoker.
        /// </summary>
        public static string IsSmoker {
            get {
                return ResourceManager.GetString("IsSmoker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Treated.
        /// </summary>
        public static string IsTreated {
            get {
                return ResourceManager.GetString("IsTreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Lab Test.
        /// </summary>
        public static string LastLabTest {
            get {
                return ResourceManager.GetString("LastLabTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like Cooking.
        /// </summary>
        public static string LikeCooking {
            get {
                return ResourceManager.GetString("LikeCooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose Weight.
        /// </summary>
        public static string LoseWeight {
            get {
                return ResourceManager.GetString("LoseWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain the Health.
        /// </summary>
        public static string MaintainTheHealth {
            get {
                return ResourceManager.GetString("MaintainTheHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscle Gain.
        /// </summary>
        public static string MuscleGain {
            get {
                return ResourceManager.GetString("MuscleGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Apple Cider.
        /// </summary>
        public static string NoAppleCider {
            get {
                return ResourceManager.GetString("NoAppleCider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pepper Added.
        /// </summary>
        public static string NoPepper {
            get {
                return ResourceManager.GetString("NoPepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Salt Added.
        /// </summary>
        public static string NoSalt {
            get {
                return ResourceManager.GetString("NoSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Description.
        /// </summary>
        public static string OtherDescription {
            get {
                return ResourceManager.GetString("OtherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Work Day Describe.
        /// </summary>
        public static string OtherWorkDayDescribe {
            get {
                return ResourceManager.GetString("OtherWorkDayDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhead Costs.
        /// </summary>
        public static string OverheadCosts {
            get {
                return ResourceManager.GetString("OverheadCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Trainer Description.
        /// </summary>
        public static string PersonalTrainerDescription {
            get {
                return ResourceManager.GetString("PersonalTrainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Locations.
        /// </summary>
        public static string PickupLocations {
            get {
                return ResourceManager.GetString("PickupLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregnancy/New Mom!.
        /// </summary>
        public static string PregnancyNewMom {
            get {
                return ResourceManager.GetString("PregnancyNewMom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Duration (minutes).
        /// </summary>
        public static string PreparingDuration {
            get {
                return ResourceManager.GetString("PreparingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Diets.
        /// </summary>
        public static string PreviousDiets {
            get {
                return ResourceManager.GetString("PreviousDiets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Factor.
        /// </summary>
        public static string PriceFactor {
            get {
                return ResourceManager.GetString("PriceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Operator.
        /// </summary>
        public static string PriceOperator {
            get {
                return ResourceManager.GetString("PriceOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Athlete/Compete.
        /// </summary>
        public static string ProfessionalAthlete {
            get {
                return ResourceManager.GetString("ProfessionalAthlete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Field.
        /// </summary>
        public static string ProfessionalField {
            get {
                return ResourceManager.GetString("ProfessionalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        public static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Diet Reason.
        /// </summary>
        public static string QuitDietReason {
            get {
                return ResourceManager.GetString("QuitDietReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        public static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Type.
        /// </summary>
        public static string RecipeType {
            get {
                return ResourceManager.GetString("RecipeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Types.
        /// </summary>
        public static string RecipeTypes {
            get {
                return ResourceManager.GetString("RecipeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturated Fat.
        /// </summary>
        public static string SaturatedFat {
            get {
                return ResourceManager.GetString("SaturatedFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedentary Hours.
        /// </summary>
        public static string SedentaryHours {
            get {
                return ResourceManager.GetString("SedentaryHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Costs.
        /// </summary>
        public static string ShoppingCosts {
            get {
                return ResourceManager.GetString("ShoppingCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Units.
        /// </summary>
        public static string SizeUnits {
            get {
                return ResourceManager.GetString("SizeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Time.
        /// </summary>
        public static string SleepTime {
            get {
                return ResourceManager.GetString("SleepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoke Description.
        /// </summary>
        public static string SmokeDescription {
            get {
                return ResourceManager.GetString("SmokeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stress Level.
        /// </summary>
        public static string StressLevel {
            get {
                return ResourceManager.GetString("StressLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stress Levels.
        /// </summary>
        public static string StressLevels {
            get {
                return ResourceManager.GetString("StressLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stringency.
        /// </summary>
        public static string Stringency {
            get {
                return ResourceManager.GetString("Stringency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudium.
        /// </summary>
        public static string Sudium {
            get {
                return ResourceManager.GetString("Sudium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugars.
        /// </summary>
        public static string Sugars {
            get {
                return ResourceManager.GetString("Sugars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        public static string Supplements {
            get {
                return ResourceManager.GetString("Supplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Supplement.
        /// </summary>
        public static string TakeSupplement {
            get {
                return ResourceManager.GetString("TakeSupplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Lipid.
        /// </summary>
        public static string TotalLipid {
            get {
                return ResourceManager.GetString("TotalLipid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Fat.
        /// </summary>
        public static string TransFat {
            get {
                return ResourceManager.GetString("TransFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin A.
        /// </summary>
        public static string VitaminA {
            get {
                return ResourceManager.GetString("VitaminA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin C.
        /// </summary>
        public static string VitaminC {
            get {
                return ResourceManager.GetString("VitaminC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size.
        /// </summary>
        public static string WaistSize {
            get {
                return ResourceManager.GetString("WaistSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wakeup Time.
        /// </summary>
        public static string WakeupTime {
            get {
                return ResourceManager.GetString("WakeupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend Describe.
        /// </summary>
        public static string WeekendDescribe {
            get {
                return ResourceManager.GetString("WeekendDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Units.
        /// </summary>
        public static string WeightUnits {
            get {
                return ResourceManager.GetString("WeightUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Day Describe.
        /// </summary>
        public static string WorkDayDescribe {
            get {
                return ResourceManager.GetString("WorkDayDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Hours.
        /// </summary>
        public static string WorkoutHours {
            get {
                return ResourceManager.GetString("WorkoutHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Period.
        /// </summary>
        public static string WorkoutPeriod {
            get {
                return ResourceManager.GetString("WorkoutPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Periods.
        /// </summary>
        public static string WorkoutPeriods {
            get {
                return ResourceManager.GetString("WorkoutPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrist Size.
        /// </summary>
        public static string WristSize {
            get {
                return ResourceManager.GetString("WristSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zinc.
        /// </summary>
        public static string Zinc {
            get {
                return ResourceManager.GetString("Zinc", resourceCulture);
            }
        }
    }
}
