//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaltStackers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Security {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Security() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaltStackers.Resources.Security", typeof(Security).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Role.
        /// </summary>
        public static string AddNewRole {
            get {
                return ResourceManager.GetString("AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to block &lt;strong&gt;{0}&lt;/strong&gt;?.
        /// </summary>
        public static string BlockConfirm {
            get {
                return ResourceManager.GetString("BlockConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block {0}.
        /// </summary>
        public static string BlockItem {
            get {
                return ResourceManager.GetString("BlockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block User.
        /// </summary>
        public static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default roles are not editable..
        /// </summary>
        public static string DefaultRoleNotEditable {
            get {
                return ResourceManager.GetString("DefaultRoleNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Role.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You can only delete the &lt;strong&gt;{0}&lt;/strong&gt; role if no user has been defined with the role. You can change users&apos; roles by changing the user management section or by clicking the edit button.&lt;/p&gt;&lt;p&gt;The following users are defined with this role in the system:&lt;/p&gt;.
        /// </summary>
        public static string DeleteRoleDescription {
            get {
                return ResourceManager.GetString("DeleteRoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some users in this role, change role of these users to delete the role..
        /// </summary>
        public static string DeleteRoleError {
            get {
                return ResourceManager.GetString("DeleteRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This title shows instead of Role name..
        /// </summary>
        public static string DisplayNameHelp {
            get {
                return ResourceManager.GetString("DisplayNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role can&apos;t be duplicate..
        /// </summary>
        public static string DuplicateRole {
            get {
                return ResourceManager.GetString("DuplicateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error verifying reCAPTCHA, please try again..
        /// </summary>
        public static string ErrorReCaptcha {
            get {
                return ResourceManager.GetString("ErrorReCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been inactivated, please contact with the system administrator..
        /// </summary>
        public static string InactivateUserLogin {
            get {
                return ResourceManager.GetString("InactivateUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is not correct..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked by the number of wrong password attempt, please try later.
        /// </summary>
        public static string LockoutError {
            get {
                return ResourceManager.GetString("LockoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to System.
        /// </summary>
        public static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Password.
        /// </summary>
        public static string LoginWithPassword {
            get {
                return ResourceManager.GetString("LoginWithPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Confirm.
        /// </summary>
        public static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        public static string NewRole {
            get {
                return ResourceManager.GetString("NewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirm.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be eight characters including one uppercase letter, one special character and alphanumeric characters..
        /// </summary>
        public static string PasswordHelpText {
            get {
                return ResourceManager.GetString("PasswordHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Recaptcha.
        /// </summary>
        public static string Recaptcha {
            get {
                return ResourceManager.GetString("Recaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha Score Threshold.
        /// </summary>
        public static string RecaptchaScoreThreshold {
            get {
                return ResourceManager.GetString("RecaptchaScoreThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCaptcha Secret Key.
        /// </summary>
        public static string ReCaptchaSecretKey {
            get {
                return ResourceManager.GetString("ReCaptchaSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCaptcha Site Key.
        /// </summary>
        public static string ReCaptchaSiteKey {
            get {
                return ResourceManager.GetString("ReCaptchaSiteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register at System.
        /// </summary>
        public static string RegisterAtSystem {
            get {
                return ResourceManager.GetString("RegisterAtSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must consist of letters and numbers. Spacing and other characters are not allowed..
        /// </summary>
        public static string RoleNameHelp {
            get {
                return ResourceManager.GetString("RoleNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permissions.
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions of Role {0}.
        /// </summary>
        public static string RolePermissions {
            get {
                return ResourceManager.GetString("RolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles List.
        /// </summary>
        public static string RolesList {
            get {
                return ResourceManager.GetString("RolesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeZone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unblock &lt;strong&gt;{0}&lt;/strong&gt;?.
        /// </summary>
        public static string UnblockConfirm {
            get {
                return ResourceManager.GetString("UnblockConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock {0}.
        /// </summary>
        public static string UnblockItem {
            get {
                return ResourceManager.GetString("UnblockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock User.
        /// </summary>
        public static string UnblockUser {
            get {
                return ResourceManager.GetString("UnblockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must start with a letter or number, Cannot contain two consecutive symbols and Must consist of between 3 to 20 allowed characters.
        /// </summary>
        public static string UsernameHelpText {
            get {
                return ResourceManager.GetString("UsernameHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users List.
        /// </summary>
        public static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
    }
}
